; Generated by Auto-GUI 3.0.1
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1
global bat := A_AppDataCommon "\bat.bat"
global tex := A_AppDataCommon "\bat.txt"
icon=
(Ltrim
"%A_ScriptDir%\267_Python-512-_1_.ico"
)
; Menu Tray, Icon, %A_ScriptDir%\267_Python-512-_1_.ico  ///UNCOMMENT IF ICON PRESET///
Gui Font, s9, Segoe UI
Gui Font
Gui Font, s14
Gui Add, Button, gbrowse x592 y152 w93 h56, Browse
Gui Font
Gui Font, s9, Segoe UI
Gui Font
Gui Font, s13
Gui Add, Edit, vLocalPythonFile x24 y16 w749 h71, %texter%
Gui Add, Edit, vArguments x24 y126 w249 h71, %tex1%--standalone --follow-imports
Gui Add, Edit, vIconLocation x294 y126 w249 h71, %tex2%--windows-icon-from-ico=%icon%
Gui Add, Link, x24 y224 w256 h30, <a href="https://nuitka.net/doc/user-manual.html#use-cases">Documentation/Guide for Nuitka</a>
Gui Add, Link, gNuitka x296 y224 w236 h30, <a href="">Install Nuitka</a>
Gui Font
Gui Font, s9, Segoe UI
Gui Font
Gui Font, s14
Gui Add, Button, gcompile x696 y152 w93 h56, Compile 
Gui Font

Gui Show, w817 h273, Compile Python with Nuitka
Return

Nuitka(CtrlHwnd, GuiEvent, LinkIndex, HrefOrID) {
  global
  FileAppend,
  (Ltrim
    pip install nuitka
    timeout /t 2
  ), %tex%
  Sleep, 50
  FileMove, %tex%, %bat%, 1
  Sleep, 120
  Run, bat.bat, %A_AppDataCommon%
  sleep 120
  FileDelete, %bat%

}

browse(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {
  global
  FileSelectFile, files
  GuiControl,, LocalPythonFile, %files%
}

compile(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {
  global
  GuiControlGet, Arguments
  GuiControlGet, IconLocation
  splitpath, files,, dir
  FileDelete, %bat%
  FileAppend,
  (Ltrim
    cd %dir%
    py -m nuitka %Arguments% %IconLocation% "%files%"
    timeout /t 10
  ), %tex%
  Sleep, 50
  FileMove, %tex%, %bat%, 1
  Sleep, 120
  Run, bat.bat, %A_AppDataCommon%
  sleep 120
  FileDelete, %bat%
}

GuiEscape:
GuiClose:
ExitApp