; Generated by Auto-GUI 3.0.1
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1
global bat := A_Desktop "\bat.bat"
global tex
Gui Font, s9, Segoe UI
Gui Font
Gui Font, s14
Gui Add, Button, gbrowse x592 y152 w93 h56, Browse
Gui Font
Gui Font, s9, Segoe UI
Gui Font
Gui Font, s13
Gui Add, Edit, vMyText x24 y16 w749 h71, %tex%
Gui Add, Edit, vMyText1 x24 y126 w249 h71, %tex1%--standalone --follow-imports
Gui Add, Edit, vMyText2 x294 y126 w249 h71, %tex2%--windows-icon-from-ico="%A_ScriptDir%\267_Python-512-_1_.ico"
Gui Add, Link, x24 y224 w336 h30, <a href="https://nuitka.net/doc/user-manual.html#use-cases">Documentation/Guide for Nuitka</a>
Gui Add, Link, gX x296 y224 w236 h30, <a href="">Install Nuitka</a>
Gui Font
Gui Font, s9, Segoe UI
Gui Font
Gui Font, s14
Gui Add, Button, gcompile x696 y152 w93 h56, Compile Python with Nuitka
Gui Font

Gui Show, w817 h273, Compile
Return

X(CtrlHwnd, GuiEvent, LinkIndex, HrefOrID) {
  global
  FileAppend,
  (Ltrim
    pip install nuitka
    timeout /t 2
  ), %bat%
  Sleep, 220
  Run, bat.bat, %A_Desktop%
  sleep 220
  FileDelete, %bat%

}

browse(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {
  global
  FileSelectFile, files
  GuiControl,, MyText, %files%
}

compile(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {
  global
  GuiControlGet, MyText1
  GuiControlGet, MyText2
  splitpath, files,, dir
  FileDelete, %bat%
  FileAppend,
  (Ltrim
    cd %dir%
    py -m nuitka %MyText1% %MyText2% "%files%"
    timeout /t 10
  ), %bat%
  Sleep, 220
  Run, bat.bat, %A_Desktop%
  sleep 220
  FileDelete, %bat%
}

GuiEscape:
GuiClose:
ExitApp
